# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-11 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': '版块', 'verbose_name_plural': '版块'},
        ),
        migrations.AlterField(
            model_name='block',
            name='desc',
            field=models.CharField(max_length=100, verbose_name='版块描述'),
        ),
        migrations.AlterField(
            model_name='block',
            name='manager_name',
            field=models.CharField(max_length=100, verbose_name='版块管理员名称'),
        ),
        migrations.AlterField(
            model_name='block',
            name='name',
            field=models.CharField(max_length=100, verbose_name='版块名称'),
        ),
    ]
