# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-11 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0002_auto_20180311_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='status',
            field=models.IntegerField(choices=[(0, '正常'), (-1, '删除')], default=0, verbose_name='状态'),
        ),
    ]
