# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-11 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0003_block_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': '板块', 'verbose_name_plural': '板块'},
        ),
        migrations.AlterField(
            model_name='block',
            name='desc',
            field=models.CharField(max_length=100, verbose_name='板块描述'),
        ),
        migrations.AlterField(
            model_name='block',
            name='manager_name',
            field=models.CharField(max_length=100, verbose_name='板块管理员名称'),
        ),
        migrations.AlterField(
            model_name='block',
            name='name',
            field=models.CharField(max_length=100, verbose_name='板块名称'),
        ),
    ]
