# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-17 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='owner',
        ),
    ]
