# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-20 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.CharField(max_length=100, verbose_name='文章'),
        ),
    ]
