# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-21 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20180320_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.IntegerField(choices=[(0, '正常'), (-1, '删除')], verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.IntegerField(choices=[(0, '正常'), (-1, '删除')], verbose_name='状态'),
        ),
    ]
