# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 02:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20180322_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
