# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20180322_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='to_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Comment', verbose_name='被回复评论'),
        ),
    ]
